maxmemory 256mb

# Khi Redis đạt đến giới hạn bộ nhớ, nó sẽ loại bỏ các khóa không được sử dụng gần đây nhất (LRU) 
# Có thời gian hết hạn (volatile) để giải phóng bộ nhớ.
maxmemory-policy volatile-lru


# RDB
# Lưu dữ liệu vào đĩa nếu có ít nhất 1 key thay đổi trong vòng 900 giây
save 900 1
# Lưu dữ liệu vào đĩa nếu có ít nhất 10 key thay đổi trong vòng 300 giây
save 300 10
# Lưu dữ liệu vào đĩa nếu có ít nhất 10000 key thay đổi trong vòng 60 giây
save 60 10000

# Đặt thư mục lưu trữ dữ liệu của Redis
dir /data

# Cấu hình Redis Cluster
port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes

# Cho phép Redis chấp nhận kết nối từ bất kỳ địa chỉ IP nào
bind 0.0.0.0
protected-mode no

# Fix networking Docker
cluster-announce-ip 127.0.0.1
cluster-announce-port 6379
cluster-announce-bus-port 16379