maxmemory 256mb

# Khi Redis đạt đến giới hạn bộ nhớ, nó sẽ loại bỏ các khóa không được sử dụng gần đây nhất (LRU) 
# Có thời gian hết hạn (volatile) để giải phóng bộ nhớ.
maxmemory-policy volatile-lru


# Lưu dữ liệu vào đĩa nếu có ít nhất 1 key thay đổi trong vòng 900 giây
save 900 1

# Lưu dữ liệu vào đĩa nếu có ít nhất 10 key thay đổi trong vòng 300 giây
save 300 10

# Lưu dữ liệu vào đĩa nếu có ít nhất 10000 key thay đổi trong vòng 60 giây
save 60 10000

dir /data