// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, search string) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	ListUsersOrderByCreatedAtAsc(ctx context.Context, arg ListUsersOrderByCreatedAtAscParams) ([]User, error)
	ListUsersOrderByCreatedAtDesc(ctx context.Context, arg ListUsersOrderByCreatedAtDescParams) ([]User, error)
	ListUsersOrderByIdAsc(ctx context.Context, arg ListUsersOrderByIdAscParams) ([]User, error)
	ListUsersOrderByIdDesc(ctx context.Context, arg ListUsersOrderByIdDescParams) ([]User, error)
	RestoreUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
