// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, fullname, age, status, level) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, uuid, email, password, fullname, age, status, level, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Fullname string `json:"fullname"`
	Age      *int32 `json:"age"`
	Status   int32  `json:"status"`
	Level    int32  `json:"level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.Fullname,
		arg.Age,
		arg.Status,
		arg.Level,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET deleted_at = NULL
WHERE uuid = $1 AND deleted_at IS NOT NULL
RETURNING id, uuid, email, password, fullname, age, status, level, deleted_at, created_at, updated_at
`

func (q *Queries) RestoreUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = NOW()
WHERE uuid = $1 AND deleted_at IS NULL
RETURNING id, uuid, email, password, fullname, age, status, level, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    password = COALESCE($1, password),
    fullname = COALESCE($2, fullname),
    age = COALESCE($3, age),
    status = COALESCE($4, status),
    level = COALESCE($5, level)
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, uuid, email, password, fullname, age, status, level, deleted_at, created_at, updated_at
`

type UpdateUserParams struct {
	Password *string `json:"password"`
	Fullname *string `json:"fullname"`
	Age      *int32  `json:"age"`
	Status   *int32  `json:"status"`
	Level    *int32  `json:"level"`
	ID       *int32  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Password,
		arg.Fullname,
		arg.Age,
		arg.Status,
		arg.Level,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.Fullname,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
