FROM golang:1.25-alpine AS builder

RUN apk update && apk --no-cache add git curl

RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code and build
COPY . .

RUN ["air"]

