CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid UUID NOT NULL DEFAULT gen_random_uuid(),
	email VARCHAR(150) UNIQUE NOT NULL,
	password VARCHAR(90) NOT NULL,
	fullname VARCHAR(100) NOT NULL,
	age INT CHECK (age >= 1 AND age <= 120),
	status INT NOT NULL DEFAULT 1 CHECK (status IN (1, 2, 3)),
	level INT NOT NULL DEFAULT 1 CHECK (level IN (1, 2, 3)),
	deleted_at TIMESTAMPTZ DEFAULT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments to columns
COMMENT ON COLUMN users.email IS 'User email address: must be unique';
COMMENT ON COLUMN users.age IS 'Age of the user: must be between 1 and 120';
COMMENT ON COLUMN users.status IS 'Status of the user: 1 - active, 2 - inactive, 3 - banned';
COMMENT ON COLUMN users.level IS 'Level of the user: 1 - administrator, 2 - moderator, 3 - member';

-- Create index
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_level ON users(level);
CREATE INDEX idx_users_created_at ON users(created_at);
CREATE INDEX idx_users_deleted_at ON users(deleted_at);
CREATE INDEX idx_users_email_status ON users(email, status);

-- Create trigger to update updated_at column on row update
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();